[package]
name = "sql-migration-connector"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1.17"
barrel = { version = "0.6.5", features = ["sqlite3", "mysql", "pg"] }
chrono = { version = "0.4" }
datamodel = { path = "../../../libs/datamodel/core" }
migration-connector = { path = "../migration-connector" }
once_cell = "1.3"
prisma-models = { path = "../../../libs/prisma-models" }
prisma-value = { path = "../../../libs/prisma-value" }
quaint = { git = "https://github.com/prisma/quaint", features = ["single", "runtime-async-std"], branch = "sqlx" }
regex = "1"
serde = "1.0"
serde_json = "1.0"
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
thiserror = "1.0.9"
async-std = "1.6.2"
tracing = "0.1.10"
tracing-futures = "0.2.0"
user-facing-errors = { path = "../../../libs/user-facing-errors", features = ["sql"] }
tracing-error = "0.1.2"
url = "2.1.1"
futures = "0.3.5"
